version: "2"

services:
  alley-oop:
    build:
      context: .
      dockerfile: Dockerfile
    image: sevesalm/alley-oop:latest
    ports:
      - "80:80"
      - "443:443"
      - "53:53/tcp"
      - "53:53/udp"
    volumes:
      - ./config:/etc/alley-oop
      - ./data:/var/lib/alley-oop
